package edu.uob;

public class TableIDTest {
    /*
    The first column in each table must contain a unique identifier or primary key (which should always be called id).
    The id value of each row will NOT be provided by the user, but rather they should be automatically generated by the server.
     */
    // TODO
}
