package edu.uob;

public class TableIDTests {
    /*
    The first column in each table must contain a unique identifier or primary key (which should always be called id).
    The id value of each row will NOT be provided by the user,
    but rather they should be automatically generated by the server.
    the id of a record should NOT change at any time during the operation of the system
    (once a record has been assigned an id this will stay fixed for as long as that record is kept in the database).
     */
    // TODO
}
